-- ============================================================
-- Paraline MSAgent — PostgreSQL Schema
-- Vexa pattern: database models for meeting/transcript storage
-- ============================================================

-- Meeting sessions
CREATE TABLE IF NOT EXISTS meeting_sessions (
    session_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    teams_meeting_id TEXT,
    teams_chat_id    TEXT,
    status           TEXT NOT NULL DEFAULT 'active',
    inbound_src_lang TEXT NOT NULL DEFAULT 'jpn_Jpan',
    outbound_tgt_lang TEXT NOT NULL DEFAULT 'jpn_Jpan',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at         TIMESTAMPTZ,
    metadata         JSONB DEFAULT '{}'
);

-- Transcript segments (Vexa: transcription segments)
CREATE TABLE IF NOT EXISTS transcript_segments (
    segment_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id      UUID NOT NULL REFERENCES meeting_sessions(session_id) ON DELETE CASCADE,
    direction       TEXT NOT NULL CHECK (direction IN ('inbound', 'outbound')),
    original_text   TEXT NOT NULL,
    translated_text TEXT NOT NULL,
    src_lang        TEXT NOT NULL,
    tgt_lang        TEXT NOT NULL,
    latency_ms      FLOAT DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Meeting minutes (generated by AI agent)
CREATE TABLE IF NOT EXISTS meeting_minutes (
    id           SERIAL PRIMARY KEY,
    session_id   UUID NOT NULL REFERENCES meeting_sessions(session_id) ON DELETE CASCADE,
    summary      TEXT NOT NULL,
    key_points   JSONB DEFAULT '[]',
    action_items JSONB DEFAULT '[]',
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Image translation logs
CREATE TABLE IF NOT EXISTS image_translations (
    id              SERIAL PRIMARY KEY,
    session_id      UUID REFERENCES meeting_sessions(session_id),
    ocr_block_count INT DEFAULT 0,
    latency_ms      FLOAT DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for fast session lookup
CREATE INDEX IF NOT EXISTS idx_segments_session ON transcript_segments(session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sessions_status  ON meeting_sessions(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_chat    ON meeting_sessions(teams_chat_id);
